// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM7EkKQw0-uxNyPtx3yufwLDNaNFy0vEU',
    appId: '1:105083301730:web:5c651d2af92d6ddf3e863b',
    messagingSenderId: '105083301730',
    projectId: 'movie-nns',
    authDomain: 'movie-nns.firebaseapp.com',
    storageBucket: 'movie-nns.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqYN6JJJzILLiYyfuvMi5wD7tUo0_ODno',
    appId: '1:105083301730:android:5a515471cba8f00c3e863b',
    messagingSenderId: '105083301730',
    projectId: 'movie-nns',
    storageBucket: 'movie-nns.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR_LOPYSKaj1tQnvkhiAns1x6lv2qYun8',
    appId: '1:105083301730:ios:09408ddccb9115b93e863b',
    messagingSenderId: '105083301730',
    projectId: 'movie-nns',
    storageBucket: 'movie-nns.appspot.com',
    iosClientId: '105083301730-quvfdlid8cd2iv75739v65g2gem66v1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR_LOPYSKaj1tQnvkhiAns1x6lv2qYun8',
    appId: '1:105083301730:ios:da23415f6f11474e3e863b',
    messagingSenderId: '105083301730',
    projectId: 'movie-nns',
    storageBucket: 'movie-nns.appspot.com',
    iosClientId: '105083301730-bu6qs743b0mh5d1k2n7n6k15ha9jnqcg.apps.googleusercontent.com',
    iosBundleId: 'com.example.movies.RunnerTests',
  );
}
